"""add_store_table

Revision ID: 37817d209584
Revises: 7cccd1020806
Create Date: 2026-02-27 22:09:03.171327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37817d209584'
down_revision = '7cccd1020806'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('business_license', sa.String(length=500), nullable=True),
    sa.Column('id_card_front', sa.String(length=500), nullable=True),
    sa.Column('id_card_back', sa.String(length=500), nullable=True),
    sa.Column('commission_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_id'), 'store', ['id'], unique=False)
    op.create_index(op.f('ix_store_user_id'), 'store', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_user_id'), table_name='store')
    op.drop_index(op.f('ix_store_id'), table_name='store')
    op.drop_table('store')
    # ### end Alembic commands ###
