"""add_tracking_no_and_remark_to_order

Revision ID: 9474fc31ab66
Revises: fc2cd177841e
Create Date: 2026-02-27 22:02:49.407577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9474fc31ab66'
down_revision = 'fc2cd177841e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('tracking_no', sa.String(length=100), nullable=True))
    op.add_column('order', sa.Column('remark', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'remark')
    op.drop_column('order', 'tracking_no')
    # ### end Alembic commands ###
