services:
  website:
    image: caryoupe-website:${VERSION:-latest}
    platform: linux/amd64
    pull_policy: never
    container_name: caryoupe-website
    restart: unless-stopped
    env_file:
      - .env.local
    expose:
      - "3000"
    networks:
      - infra_lyz

networks:
  infra_lyz:
    external: true
